BaseUrl: "http://example.com"
LanguageCode: "en-us"
Title: "djouxtech"

Params:
  Author: "Your name."
  DateForm: "Mon, Jan 2, 2006"
  Piwik: "stats.vm1.com"
  Facebook: "Your ID."
  Twitter: "Your ID."
  Github: "Your ID."
  ShowRelatedPost: True
  Disqus: "djouxtech"
  SyntaxHighlightTheme: "solarized_dark.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"

